---
- name: Playbook para instalar o Datadog Agent e o NGINX no Amazon Linux
  hosts: your_aws_instance
  become: true
  tasks:
    # 1. Instalar o Datadog Agent usando a coleção do Ansible
    - name: Instalar o Datadog Agent
      import_role:
        name: datadog.dd.agent
      vars:
        datadog_api_key: "<YOUR_DATADOG_API_KEY>"  # Substitua pela sua chave da API do Datadog
        datadog_site: "datadoghq.com"  # Você pode mudar para "datadoghq.eu" se estiver na região da UE

    # 2. Instalar o NGINX
    - name: Instalar o NGINX
      yum:
        name: nginx
        state: present

    - name: Iniciar e habilitar o serviço NGINX
      systemd:
        name: nginx
        state: started
        enabled: true

    - name: Verificar o status do NGINX
      command: systemctl status nginx
      register: nginx_status

    - name: Mostrar status do NGINX
      debug:
        var: nginx_status
